# This is a basic workflow to help you get started with Actions

name: Build CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build App and OS
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v5.1
        target: esp32c6
        path: '.'
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Firmware
        path: |
          /app/mtribiere/CoffeeInterceptor/build/bootloader/bootloader.bin
          /app/mtribiere/CoffeeInterceptor/build/partition_table/partition-table.bin
          /app/mtribiere/CoffeeInterceptor/build/uart_echo.bin
